#=@enum Prods ATRIB_=1 CT_NUM_ OPR_ARIT_ OPR_SUMSUB_ OPRLR_EQ_DIF_ OPRLR_LGTR_ OPRLR_GTR_ OPRL_ANDOR_ BOOLEAN_ INT_DCLR_ EXPR_ARIT_ OPR_LOGIC_ EXPR_BOOL_ LOOP_WHILE_ LOOP_FOR_ LOOP_ CMD_ DATA_TYPE_ PARAMS_R_ PARAMS_ MAIN_ FN_DCLR_ S_ TERM_NUM_ EXP_ARIT_ EXPR_ALG_ OPRLR_LGT_ OPRLR_G_ OPRLR_ FN_CALL_=#

@enum Prods S_=1 TYPE_ PARAM_ P1_ IDVEC_ ALL_INTER_ RIF_ RIF1_ ATTR_ RWHILE_ RFOR_ RCONT_ EXPR_ALL_ EXPR_I_F_ EX1_ EX11_ EX2_ EXPR_BOOL_ EXB1_ EXB11_ EXB2_ EXPR_STR_ EXS1_ EXS2_

function Production(subprods_)
	prd = Production(subprods_)
end

