using DataStructures
using JSON


@enum Tokens CT_VALUE=1 CT_INT CT_CHAR CT_FLOAT CT_VEC SMCL EPS ID CONST EXPR OPR_PM OPR_DM OPRLN OPRLR_EQ OPRLR_LG OPRLR_LGEQ FN_PRINT FN_READ DRED BLK_IF BLK_ELS BLK_FOR BLK_WHILE COMMA O_BRCKT C_BRCKT O_C_BRCKT C_C_BRCKT O_PRTSIS C_PRTSIS OPR_ATR IDT_INT IDT_FLOAT IDT_CHAR IDT_STRING FN_MAIN VEC_IN LEX_ERR OPR_SUM OPR_SUB CTN PARAMS_Tk IDT_BOOL EXP_BOOL VOID FN_DCLR FN_CALL_TK CT_STRING OPR_UN_NEG OPRLR_GT RETURN OPRLR_GEQ OPR_CONCAT OPRLR_AND OPRLR_OR OPRL_NOT CTB CMNT_LN CONTINUE BREAK OPRLR_DIF EOF CT_STR


tks_names = String[]

for tk in instances(Tokens)
	push!(tks_names,string(tk))
end

#f = open("tks.json","w+")
#write(f,String(JSON.json(tkns_nms)))
#flush(f)
#close(f)